version: '3.9'

services:
  vm:
    container_name: 'lisa-vm'
    build: ./bot
    image: registry.zero-team.pro/lisa/bot:${TAG-latest}
    restart: always
    env_file: .env
    command: 'yarn run start-vm'
    volumes:
      - './.env:/app/.env:ro'
      - '${DATA_MOUNT_PATH}/certs/:/certs:ro'
      - '${DATA_MOUNT_PATH}/vm/:/data'
      - '/var/run/docker.sock:/var/run/docker.sock'
