version: '3.9'

services:
  bot-gateway:
    container_name: 'lisa-bot-gateway'
    build: ./bot
    image: registry.zero-team.pro/lisa/bot:${TAG-latest}
    restart: always
    env_file: .env
    command: 'yarn run start-gateway'
    networks:
      - default
      - nginx-proxy
    volumes:
      - './.env:/app/.env:ro'
      - '${DATA_MOUNT_PATH}/certs/:/certs:ro'
    environment:
      - SHARD_COUNT=2
      - DB_FORCE=${DB_FORCE}
      - VIRTUAL_HOST=${API_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${API_HOST_LE}
    depends_on:
      - 'db'
      - 'redis'

  bot-shard-0:
    container_name: 'lisa-bot-shard-0'
    build: ./bot
    image: registry.zero-team.pro/lisa/bot:${TAG-latest}
    restart: always
    env_file: .env
    command: 'yarn run start-cluster'
    volumes:
      - './.env:/app/.env:ro'
      - '${DATA_MOUNT_PATH}/certs/:/certs:ro'
    environment:
      - SHARD_ID=0
      - SHARD_COUNT=2
    depends_on:
      - 'db'
      - 'redis'

  bot-shard-1:
    container_name: 'lisa-bot-shard-1'
    build: ./bot
    image: registry.zero-team.pro/lisa/bot:${TAG-latest}
    restart: always
    env_file: .env
    command: 'yarn run start-cluster'
    volumes:
      - './.env:/app/.env:ro'
      - '${DATA_MOUNT_PATH}/certs/:/certs:ro'
    environment:
      - SHARD_ID=1
      - SHARD_COUNT=2
    depends_on:
      - 'db'
      - 'redis'

  bot-telegram-0:
    container_name: 'lisa-bot-telegram-0'
    build: ./bot
    image: registry.zero-team.pro/lisa/bot:${TAG-latest}
    restart: always
    env_file: .env
    command: 'yarn run start-telegram'
    profiles: ['telegram']
    volumes:
      - './.env:/app/.env:ro'
      - '${DATA_MOUNT_PATH}/certs/:/certs:ro'
    environment:
      - SHARD_ID=0
    depends_on:
      - 'db'
      - 'redis'

  rater:
    container_name: 'lisa-rater'
    build: ./rater
    image: registry.zero-team.pro/lisa/rater:${TAG-latest}
    restart: always
    env_file: .env
    profiles: ['rater']
    volumes:
      - './.env:/app/.env:ro'

  db:
    container_name: 'lisa-postgresql'
    build: ./db
    image: registry.zero-team.pro/lisa/db:${TAG-latest}
    restart: always
    env_file: .env
    ports:
      - '9302:5432'
    volumes:
      - '${DATA_MOUNT_PATH}/postgres/:/var/lib/postgresql/data/'

  redis:
    container_name: 'lisa-redis'
    image: zeroteampro/redis:v7.0.11
    restart: always
    env_file: .env
    ports:
      - '9343:6379'
    volumes:
      - '${DATA_MOUNT_PATH}/certs/redis/:/certs'
      - '${DATA_MOUNT_PATH}/redis/:/data'
    environment:
      - REDIS_MAX_MEMORY=256mb
      - REDIS_TLS_GEN=true
      - REDIS_TLS_ON=true

  postgres-exporter:
    container_name: 'lisa-postgres-exporter'
    build: ./devops/postgres-exporter
    image: registry.zero-team.pro/lisa/postgres-exporter:${TAG-latest}
    restart: always
    env_file: .env
    profiles: ['monitor']
    ports:
      - '19187:9187'
    depends_on:
      - db

  admin:
    container_name: 'lisa-admin'
    build:
      context: ./admin
      args:
        REACT_APP_API_HOST: ${API_HOST}
        REACT_APP_API_HOST_LE: ${API_HOST_LE}
    image: registry.zero-team.pro/lisa/admin:${TAG-latest}
    restart: always
    env_file: .env
    profiles: ['admin']
    networks:
      - default
      - nginx-proxy
    volumes:
      - './admin/test/screenshots:/app/test/screenshots'
    environment:
      - VIRTUAL_HOST=${ADMIN_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${ADMIN_HOST_LE}
    depends_on:
      - 'bot-gateway'

networks:
  default:
    name: lisa
  nginx-proxy:
    name: nginx-proxy
    external: true
