export const translationEnglish = {
  commandNotFound: 'Command not found',
  wrongParams: 'Wrong params',
  none: 'none',
  dbError: 'DB error',
  enabled: 'enabled',
  enabled_plural: 'enabled',
  disabled: 'disabled',
  disabled_plural: 'disabled',
  notAdminError: 'Administrator rights required',
  help: {
    general: 'help text',
    title: 'Help',
    sectionList: 'List of help sections',
    config: 'TBD: help config',
    lang: 'TBD: help lang',
    preset: 'TBD: help preset',
    notFound: 'Section in help pages not found',
  },
  lisa: {
    listening: 'Listening',
  },
  config: {
    channels: {
      title: 'Channels',
      all: 'All channels',
      enabledList: 'Enabled channels',
      count: 'New channels count',
      noMain: 'No main channel',
      main: 'Main channel: {{channel}} _{{id}}_',
      cantFindInDB: "Can't find channel in DB",
      cantFindInDiscord: "Can't find channel in Discord",
      newMain: 'New main channel: {{channel}} _{{id}}_',
      stateChange: 'Channel {{channel}} _{{id}}_ **{{state}}**',
      enabledAll: 'All channels in DB **{{state}}**',
    },
    prefix: {
      server: `This server prefix: {{prefix}}"`,
      oneSymbol: 'Server prefix should be just one symbol.',
      changedTo: 'Server prefix changed to: "{{prefix}}"',
    },
    initComplete: 'Init complete',
    wrongParams: 'Wrong config command/params',
  },
  lang: {
    changed: 'Language changed',
    wrongLang: 'Wrong lang',
    wrongParams: 'Wrong params or lang',
  },
  preset: {
    userPresetTitle: 'Your preset list',
    serverPresetTitle: 'Server preset list',
    statsError: 'Stats check error',
    userCreatedTitle: 'Preset created',
    serverCreatedTitle: 'Preset created for server',
    notFound: 'Preset not found',
    deleted: 'Preset deleted',
  },
  external: {
    notAvailable: 'This command not available for some reason',
    processingError: 'Error while processing external command',
  },
};
