ALTER TABLE public.ai_owner
ADD COLUMN "model" VARCHAR NULL DEFAULT NULL,
ADD COLUMN "modelTools" VARCHAR NULL DEFAULT NULL,
ADD COLUMN "isToolsEnabled" BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN "maxTokens" INTEGER NULL DEFAULT NULL;
